# -*- coding: utf-8 -*-
"""Galois-C7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGi944FPmpfXV58DDBtOzG2RxIrqTz8R
"""

#works better for larger prime p :
# SageMath: degree-7 C7 polynomials via Gaussian periods (no subfields() calls)

from sage.all import *
import csv

def degree7_subfield_polynomial_via_period(p):
    """
    Return the minimal polynomial over Q of a Gaussian period that generates
    the unique degree-7 subfield of Q(zeta_p), for p ≡ 1 mod 7.
    """
    if p % 7 != 1 or not is_prime(p):
        raise ValueError(f"p must be prime with p ≡ 1 mod 7; got p={p}")

    K = CyclotomicField(p)
    z = K.gen()

    # multiplicative generator g of (Z/pZ)^×, viewed as an integer representative
    g_mod = Integers(p).multiplicative_generator()
    g = int(g_mod)  # primitive root modulo p

    # H = <g^7> is the unique subgroup of index 7 (order (p-1)/7)
    m = (p - 1) // 7
    # Representatives of H itself (the coset with j = 0):
    exps = [pow(g, 7*k, p) for k in range(m)]   # distinct mod p, in {1,...,p-1}

    # Gaussian period for the coset H (you can also use j=1..6; any gives the same field)
    eta = sum(z**e for e in exps)

    # Minimal polynomial over Q; coefficients are integers
    f = eta.minpoly().change_ring(QQ)
    return f

def generate_C7_polynomials(prime_bound, quiet=False):
    """
    For primes p ≤ prime_bound with p ≡ 1 (mod 7),
    generate defining polynomials of the unique degree-7 subfield of Q(zeta_p).
    Returns a list of tuples: (p, polynomial, coefficient_tuple).
    """
    results = []
    for p in primes(prime_bound):
        if p % 7 != 1:
            continue
        if not quiet:
            print(f"Processing p={p} ...", flush=True)
        try:
            f = degree7_subfield_polynomial_via_period(p)
            coeffs = tuple(f.coefficients(sparse=False))
            results.append((p, f, coeffs))
            if not quiet:
                print(f"  found degree-7 C7 polynomial: {f}")
        except Exception as e:
            # Very rare, but catch and continue
            print(f"  skipped p={p} due to error: {e}")
    return results

# -------- Example run --------
# If you *really* insist on using PARI-heavy routines later, you can bump PARI memory:
# from cypari2 import pari; pari.allocatemem("2G")

polynomial_data = generate_C7_polynomials(50000, quiet=False)

# Save to CSV
with open("C7_polynomials.csv", "w", newline="") as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(["p", "Polynomial", "Coefficient Tuple"])
    for p, poly, coeff_tuple in polynomial_data:
        writer.writerow([p, str(poly), coeff_tuple])

print(f"Generated {len(polynomial_data)} degree-7 polynomials with Galois group C7.")